# Generated by Django 2.0.3 on 2018-03-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartment',
            name='mynumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
