# Generated by Django 2.0.3 on 2018-03-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_compartment_mynumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compartment',
            name='mynumber',
        ),
    ]
