# Generated by Django 2.0.3 on 2018-04-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_remove_compartment_mynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='comment',
            field=models.TextField(blank=True, help_text='Enter a comment if you want'),
        ),
    ]
