# Generated by Django 2.0.3 on 2018-04-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_auto_20180417_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='box',
            field=models.CharField(default='Test Box', max_length=50),
            preserve_default=False,
        ),
    ]
