# Generated by Django 2.0.3 on 2018-04-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_auto_20180417_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tube',
            options={'ordering': ['yvalue', 'xvalue']},
        ),
    ]
