# Generated by Django 2.0.3 on 2018-04-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_auto_20180419_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='tubes_in_a_row',
        ),
        migrations.RemoveField(
            model_name='document',
            name='tubes_in_a_row',
        ),
    ]
