# Generated by Django 2.0.3 on 2018-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_auto_20180419_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='code',
            field=models.CharField(blank=True, choices=[('eu', 'EU'), ('us', 'US')], max_length=50),
        ),
        migrations.AddField(
            model_name='type',
            name='eu_color',
            field=models.CharField(blank=True, choices=[('serum', 'Serum'), ('serum-gel', 'Serum-Gel'), ('lithium-heparin', 'Lithium-Heparin'), ('flouride', 'flouride'), ('edta ke', 'EDTA KA'), ('citrat bsg', 'Citrat BSG'), ('citrat coagulation', 'Citrat coagulation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='compartment',
            name='space',
            field=models.IntegerField(help_text='Enter how many racks/boxes can store in the compartment'),
        ),
        migrations.AlterUniqueTogether(
            name='tube',
            unique_together={('yvalue', 'xvalue', 'box')},
        ),
    ]
