# Generated by Django 2.0.3 on 2018-04-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0012_auto_20180424_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='eu_color',
            new_name='color',
        ),
    ]
