# Generated by Django 2.0.3 on 2018-04-26 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_auto_20180426_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
