# Generated by Django 2.0.3 on 2018-04-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hartmaring', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
