# Generated by Django 2.0.3 on 2018-04-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='August', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Peter', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Simon', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(blank=True, choices=[('cerulean', 'Cerulean'), ('cosmo', 'Cosmo'), ('cyborg', 'Cyborg'), ('darkly', 'Darkly'), ('flatly', 'Flatly'), ('journal', 'Journal'), ('lietra', 'Lietra'), ('lumen', 'Lumen'), ('lux', 'Lux'), ('materia', 'Matria'), ('minty', 'Minty'), ('pulse', 'Pulse'), ('sandstone', 'Sandstone'), ('simplex', 'Simplex'), ('sketchy', 'Sketchy'), ('slate', 'Slate'), ('solar', 'Solar'), ('spacelab', 'Spacelab'), ('superhero', 'Superhero'), ('united', 'United'), ('yeti', 'Yeti')], max_length=50),
        ),
    ]
